### ISSUE TITLE
Error with Notebook #2

### ISSUE THREAD

**Issue by ljbennett62** [watson-developer-cloud/answer-retrieval#16]
- In the second notebook, step 2 of step 5 tells you to do something to a file, but not how to do it. 
- The whole of the second notebook cannot be run. When the second step is run, it immediately comes back with: 
  “Directory '.' is not installable. File 'setup.py' not found.
  Requirement 'retrieve_and_rank_scorer-1.0-py2-none-any.whl' looks like a filename, but the file does not exist
  Processing ./retrieve_and_rank_scorer-1.0-py2-none-any.whl
  Exception:
  Traceback (most recent call last):
    File "/Users/mwassel/miniconda2/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
      status = self.run(options, args)
    File "/Users/mwassel/miniconda2/lib/python2.7/site-packages/pip/commands/install.py", line 310, in run
      wb.build(autobuilding=True)
    File "/Users/mwassel/miniconda2/lib/python2.7/site-packages/pip/wheel.py", line 750, in build
      self.requirement_set.prepare_files(self.finder)
    File "/Users/mwassel/miniconda2/lib/python2.7/site-packages/pip/req/req_set.py", line 370, in prepare_files
      ignore_dependencies=self.ignore_dependencies))
    File "/Users/mwassel/miniconda2/lib/python2.7/site-packages/pip/req/req_set.py", line 587, in _prepare_file
      session=self.session, hashes=hashes)
    File "/Users/mwassel/miniconda2/lib/python2.7/site-packages/pip/download.py", line 798, in unpack_url
      unpack_file_url(link, location, download_dir, hashes=hashes)
    File "/Users/mwassel/miniconda2/lib/python2.7/site-packages/pip/download.py", line 705, in unpack_file_url
      unpack_file(from_path, location, content_type, link)
    File "/Users/mwassel/miniconda2/lib/python2.7/site-packages/pip/utils/__init__.py", line 599, in unpack_file
      flatten=not filename.endswith('.whl')
    File "/Users/mwassel/miniconda2/lib/python2.7/site-packages/pip/utils/**init**.py", line 482, in unzip_file
      zipfp = open(filename, 'rb')
  
  IOError: [Errno 2] No such file or directory: '/Users/mwassel/Downloads/answer-retrieval-master/notebooks/retrieve_and_rank_scorer-1.0-py2-none-any.whl’” 
  in the output terminal that is running the notebook. After that step, all other steps come back with similar responses.

**Comment by lkrishnamurthy** [comment]
Unable to re-create locally. Also, the developers I contacted didn't seem to have this issue.

**Comment by lkrishnamurthy** [comment]
Fixed. The error was due to the snippet pointing to the wrong directory. Modified and verified the same to be working.
